dist: trusty
language:
  - python
compiler: g++
python:
  - 2.7
addons:
  apt:
    packages:
    - libpython2.7
    - libpython2.7-dev
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-lang-german
    - texlive-fonts-recommended
    - texlive-latex-extra

before_install:
  - sudo apt-get update
  - sudo pip install pip setuptools numpy matplotlib requests
  - git clone https://github.com/hiaselhans/OpenGlider.git
  - cd OpenGlider
  - sudo python setup.py install
  - cd ..
  - hg clone https://bitbucket.org/eigen/eigen
  - sudo mkdir /usr/include/eigen3/
  - sudo cp eigen/Eigen/  /usr/include/eigen3/Eigen -r
  - sudo cp eigen/signature_of_eigen3_matrix_library /usr/include/eigen3/
  - git clone https://github.com/pybind/pybind11.git
  - sudo cp pybind11/include/pybind11 /usr/include/python2.7/ -r
  - git clone https://github.com/looooo/paraEigen.git
  - cd paraEigen
  - sudo python setup.py install
  - cd ..
install:
  - sudo python setup.py install
  - sh ./run_all.sh python
  - sh ./create_doc.sh

branches:
  only:
    - master