# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'nothing.'
url:                 http://booya-at.github.io/paraBEM/
baseurl:             '/paraBEM'

# set limit on number of post to appear on Home page
homepostlimit:        4

# About/contact
author:
  name:              Mark Otto
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
