# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MY
tagline:             'blog'
description:         'browse the blog'
url:                 http://booya-at.github.io/
baseurl:             '/paraBEM'

gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              looooo
  email:             sppedflyer@gmail.com

# Custom vars
version:             1.0.0
