package:
  name: parabem
  version: 0.0.1

build:
  number: 1

source:
  path: ../

requirements:
  build:
    - cmake
    - python
    - eigen                 #   - https://conda.anaconda.org/rmg
    - pybind11              #   - https://conda.anaconda.org/pybind
  run:
    - paraeigen             #   - https://conda.anaconda.org/looooo
    - python
    - numpy
    - matplotlib

about:
  summary: potential flow with boundary elements.