package:
  name: parabem
  version: 0.0.1

build:
  number: 0

source:
  path: ../

requirements:
  build:
    - cmake
    - python
    - eigen
    - pybind11
  run:
    - python
    - numpy
    - matplotlib
    - paraEigen

about:
  summary: potential flow with boundary elements.